name: Deadline Status Checker

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  trigger-local-task:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to local server
        run: |
          curl -X POST http://127.0.0.1:5000/run_task