name: Deadline Status Checker

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  check_deadlines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask sqlalchemy psycopg2 flask-cors flask-socketio flask_sqlalchemy  # Updated to include flask_sqlalchemy
          # Add any other necessary packages here

      - name: Check and update deadlines
        run: python check_deadlines.py